name: Cleanup Actions History

on:
  push:
    branches:
      - master

jobs:
  delete-workflow:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete Old Workflow Runs via API
        run: |
          curl -X GET -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs" | jq -r '.workflow_runs[].id' | \
            xargs -I {} curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/{}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
